### ISSUE TITLE
Ne radi na android box, x96

### ISSUE THREAD

**Issue by rsimac** [rsimac/kodi_plugin_hrti#1]
Prijavljeno na http://www.kodi.com.hr/topic/hrti-kodi-plugin/#post-4755, hvala korisniku alen

`ne radi, isprobano na Kodi 16, android box x96`

**Comment by rsimac** [comment]
* Testirano na android telefonu, Android 5.0.2.
* Kodi 17 downloadan sa google play, 
* plugin downloadan sa ovog sucelja, 

Sve je funkncionalno, nisam vidio nikakvih problema.

Nazalost ne posjedujem 'android box x96' tako da ne mogu testirati na istoj platformi.

Ako ste u mogucnosti naci/poslati kodi.log sa problematicnog uredjaja, mozemo probati rijesiti...

**Comment by abajo** [comment]
Jučer isto isprobano na kompu, Kodi 17, radi besprijekorno. Inače svaka pohvala na trudu!
Evo dijela loga gdje se javlja hrti:

09:12:09 T:18446744072985037104   DEBUG: CPythonInvoker(14, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.hrti/hrti.py): the source file to load is "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.hrti/hrti.py"
09:12:09 T:18446744072985037104   DEBUG: CPythonInvoker(14, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.hrti/hrti.py): setting the Python path to /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.hrti:/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib:/:/data/app/org.xbmc.kodi-1/base.apk/assets/python2.6/lib/python26.zip:/data/app/org.xbmc.kodi-1/base.apk/assets/python2.6/lib/python2.6:/data/app/org.xbmc.kodi-1/base.apk/assets/python2.6/lib/python2.6/plat-linux3:/data/app/org.xbmc.kodi-1/base.apk/assets/python2.6/lib/python2.6/lib-tk:/data/app/org.xbmc.kodi-1/base.apk/assets/python2.6/lib/python2.6/lib-old:/data/app/org.xbmc.kodi-1/base.apk/assets/python2.6/lib/python2.6/lib-dynload
09:12:09 T:18446744072985037104   DEBUG: CPythonInvoker(14, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.hrti/hrti.py): entering source directory /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.hrti
09:12:09 T:18446744072985037104   DEBUG: CPythonInvoker(14, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.hrti/hrti.py): instantiating addon using automatically obtained id of "plugin.video.hrti" dependent on version 0.0.0 of the xbmc.python api
09:12:09 T:18446744073105844528  NOTICE: DudeHere Common Routines: DHCR Service Starting...
09:12:09 T:18446744072985037104   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.SyntaxError'>
                                            Error Contents: ('invalid syntax', ('/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.hrti/hrti.py', 324, 23, "    keys = {'username', 'password', 'catalog_uri', 'category_uri', 'playlist_uri','img_uri', 'login_uri', 'uuid_uri', 'search_uri', 'live_uri', 'live_mpd'}\n"))
                                            SyntaxError: ('invalid syntax', ('/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.hrti/hrti.py', 324, 23, "    keys = {'username', 'password', 'catalog_uri', 'category_uri', 'playlist_uri','img_uri', 'login_uri', 'uuid_uri', 'search_uri', 'live_uri', 'live_mpd'}\n"))
                                            -->End of Python script error report<--

**Comment by rsimac** [comment]
@abajo hvala puno na detaljnom izvjescu.

Pokusao sam popraviti problematicnu liniju, sada koristim listu umjesto dict, cini mi se ispravnijim, ali nisam 100% siguran da li ce rijesiti problem na tvojem deviceu.
Ako zelis, probaj ponovno downloadati plugin i reinstalirati, pa da vidimo da li radi.
Hvala

**Comment by abajo** [comment]
Nažalost, na oba uređaja ne radi.
1. Android 4, Kodi 16.1
2. Android 6, Kodi 16.1
Ponavljam, na kod 17 radi savršeno.

**Comment by rsimac** [comment]
Hmm, tvrd problem.
Evo sad sam isprobao na ubuntu 16.04 (linux pa rekoh najblize androidu),, Kodi 15.1, Kodi 16.1, Kodi 17, i sve jednostavno radi...
Ako je dostupan svjezi log file, posaljite, mozda je sada neka nova greska... Hvala na reportima...

**Comment by abajo** [comment]
Ponovno sam reistalirao Kodi, isprobao i opet se ruši, evo sveži log:

09:52:45 T:18446744073429616944   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.hrti/)
09:52:45 T:18446744073429616944   DEBUG:   ParentPath = [plugin://plugin.video.hrti/]
09:52:45 T:18446744073429616944   DEBUG: bool XFILE::CPluginDirectory::StartScript(const string&, bool) - calling plugin HRTi('plugin://plugin.video.hrti/','1','')
09:52:45 T:18446744073429616944   DEBUG: bool XFILE::CPluginDirectory::WaitOnScriptResult(const string&, int, const string&, bool) - waiting on the HRTi (id=6) plugin...
09:52:45 T:18446744073051568432   DEBUG: Thread LanguageInvoker start, auto delete: false
09:52:45 T:18446744073051568432    INFO: initializing python engine.
09:52:45 T:18446744073051568432   DEBUG: CPythonInvoker(6, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.hrti/hrti.py): start processing
09:52:45 T:18446744073051568432   DEBUG: -->Python Interpreter Initialized<--
09:52:45 T:18446744073051568432   DEBUG: CPythonInvoker(6, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.hrti/hrti.py): the source file to load is "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.hrti/hrti.py"
09:52:45 T:18446744073051568432   DEBUG: CPythonInvoker(6, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.hrti/hrti.py): setting the Python path to /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.hrti:/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib:/:/data/app/org.xbmc.kodi-1/base.apk/assets/python2.6/lib/python26.zip:/data/app/org.xbmc.kodi-1/base.apk/assets/python2.6/lib/python2.6:/data/app/org.xbmc.kodi-1/base.apk/assets/python2.6/lib/python2.6/plat-linux3:/data/app/org.xbmc.kodi-1/base.apk/assets/python2.6/lib/python2.6/lib-tk:/data/app/org.xbmc.kodi-1/base.apk/assets/python2.6/lib/python2.6/lib-old:/data/app/org.xbmc.kodi-1/base.apk/assets/python2.6/lib/python2.6/lib-dynload
09:52:45 T:18446744073051568432   DEBUG: CPythonInvoker(6, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.hrti/hrti.py): entering source directory /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.hrti
09:52:45 T:18446744073051568432   DEBUG: CPythonInvoker(6, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.hrti/hrti.py): instantiating addon using automatically obtained id of "plugin.video.hrti" dependent on version 0.0.0 of the xbmc.python api
09:52:45 T:18446744073051568432   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.SyntaxError'>
                                            Error Contents: ('invalid syntax', ('/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.hrti/hrti.py', 324, 23, "    keys = {'username', 'password', 'catalog_uri', 'category_uri', 'playlist_uri','img_uri', 'login_uri', 'uuid_uri', 'search_uri', 'live_uri', 'live_mpd'}\n"))
                                            SyntaxError: ('invalid syntax', ('/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.hrti/hrti.py', 324, 23, "    keys = {'username', 'password', 'catalog_uri', 'category_uri', 'playlist_uri','img_uri', 'login_uri', 'uuid_uri', 'search_uri', 'live_uri', 'live_mpd'}\n"))
                                            -->End of Python script error report<--
09:52:45 T:18446744073051568432    INFO: Python script stopped

Ali ako neide, neide, bit će mi žao jer sa aplikacijom HRTi sa GP-a isto nemam sreće.
Pozdrav, Alen

**Comment by rsimac** [comment]
hmm tu mi je nesto sumnjivo...
zadnji log ima istu gresku kao i prvi log, ista linija, ista (kriva) sintaxa, koju sam popravio...
`
Error Contents: ('invalid syntax', ('/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.hrti/hrti.py', 324, 23, " keys = {'username', 'password', 'catalog_uri', 'category_uri', 'playlist_uri','img_uri', 'login_uri', 'uuid_uri', 'search_uri', 'live_uri', 'live_mpd'}\n"))
`

sto moze znaciti da se plugin nije updatirao/refreshao, sa novijom verzijom... Nova verzija bi trebala imati ovakvu liniju (uglate zagrade):
`" keys = ['username', 'password', 'catalog_uri', 'category_uri', 'playlist_uri','img_uri', 'login_uri', 'uuid_uri', 'search_uri', 'live_uri', 'live_mpd']`

E sad zasto se nije updatiralo... to neznamo... ja sam testirao i updates i 'sve radi'... 
Hvala na testu i logovima...

**Comment by dankec2000** [comment]
Kod mene se na LibreELEC-u (na M8S+ android box-u) također ne update-a novijom verzijom. Niti auto niti ručno. Danas ću provjeriti da li radi "search history", ali morao sam downloadati novi repository

**Comment by rsimac** [comment]
Hmm, ako dobro razumijem, rijec je o 'update' funkciji.
Ja mislim da ovakav repository gdje se zbog prirode githuba mora downloadati .zip file, ne podrzava 'update' kao takav, nego je svaka instalacija u bit 'nova' instalacija iz nove .zip datoteke kako je opisano u readme od ovog projekta.
Napominjem da ce svi korisnicki podaci, username, password a ubuduce i search history biti sacuvani tijekom takve 'nove' instalacije iz zip datoteke.
Hvala na testingu i reportu i javite ako ovo sto sam napisao stoji.

**Comment by muzena** [comment]
@rsimac 

[Using Github for an Kodi add-on repository](https://forum.kodi.tv/showthread.php?tid=219225)
[ HOW-TO:Create a repository for add-ons ](http://kodi.wiki/view/HOW-TO:Create_a_repository_for_add-ons)

**Comment by rsimac** [comment]
Zatvorit cu ovaj issue, kad budem imao vremena nastaviti cu sa issue #4
