### ISSUE TITLE
Dodati "search history" da ne moramo svaki put iznova upisivati pojam za pretragu

### ISSUE THREAD

**Issue by dankec2000** [rsimac/kodi_plugin_hrti#3]

**Comment by rsimac** [comment]
Po komentaru od @dankec2000 

> Radi odlično na M8S+ pod LibreElec. Može li se dodati "search history" da ne moramo svaki put iznova upisivati pojam za pretragu?

Hvala na prijedlogu, pogledati cu sto se moze napraviti pa javim ovdje.

**Comment by rsimac** [comment]
Rijeseno. Dodana nova stavka u izborniku "Povijest Pretraga". Testirano na kodi 17.3, windows. 
addon zip file updated, instalacija/update je jednaka kao za nove verzije, svi prethodni podaci (username/passwd etc) ostaju netaknuti.
Ako moze javite da li radi ok i na kojim platformama da imamo za reference. Hvala!

**Comment by dankec2000** [comment]
Olicno radi na M8S+ (LibreELEC). Nisam isprobao koliko stavki povijest pamti, tj, kad se najstarije pocinju zamjenjivati novima? Za buducnost (eventualno) mogu predloziti brisanje nekih stavki s liste ili lock drugih. Isto tako, ako ste voljni dalje razvijati, mogli bi razmisliti o "my favorites" folderu i dodavanju stavki u nju.

**Comment by rsimac** [comment]
Je to su dobri prijedlozi vidjet cu sto se moze napraviti. Hvala na testingu i potvrdi. Ovo je jednostavna implementacija, i povijest ce se pamtiti 'zauvijek' :). Ako bi povijest ikada postala problem bilo velicinom ili sadrzajem, moguce bi bilo editirati plugin settings datoteku gdje se povijest pohranjuje, na mojem ubuntu linuxu se nalazi u mojem home folderu (na drugim instalacijama moze biti drugdje):
`.kodi/userdata/addon_data/plugin.video.hrti/settings.xml`

Unutar te datoteke nalazi se linija `search_history` sa poljem `value` koji sadrzi listu pretraga.  Uz primjeren oprez ta se linija moze editirati rucno, na primjer za pobrisati 'zagreb':

`<setting id="search_history" value='[&quot;zagreb&quot;, &quot;rijeka&quot;]' />`

`<setting id="search_history" value='[&quot;rijeka&quot;]' />`
